site_name: "LevelUp: AI Foundations"
site_url: https://founder-fieldnotes.github.io/levelup-courses

# Tell MkDocs where your markdown lives
docs_dir: courses/ai-foundations/docs
# Optional: keep the build output with the course
site_dir: courses/ai-foundations/site

theme:
  name: material
  palette:
    - scheme: slate
      primary: black
      accent: amber
    - scheme: default
      primary: black
      accent: amber
  features:
    - navigation.sections
    - navigation.instant
    - navigation.top
    - content.code.copy

# All CSS/JS paths are now relative to docs_dir
extra_css:
  - styles/extra.css
  - assets/embed.css
extra_javascript:
  - assets/embed.js

nav:
  - Welcome: index.md
  - Module 1: module-1.md
  - Module 2: module-2.md

plugins:
  - git-revision-date-localized
