site_name: AI Foundations
site_description: LevelUp Academy | AI Foundations Course
site_url: https://founder-fieldnotes.github.io/levelup-courses/ai-foundations/
repo_url: https://github.com/founder-fieldnotes/levelup-courses
repo_name: levelup-courses
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - content.code.copy
    - toc.integrate
    - search.suggest
    - search.highlight
  language: en
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

nav:
  - Overview: index.md
  - Syllabus: syllabus.md
  - Logistics: logistics.md
  - Assessments: assessments.md
  - Modules:
    - "01 · Dev Environment & Collaboration": modules/01-dev-env.md
    - "02 · Programming for AI/DS": modules/02-programming.md
    - "03 · NLP Core": modules/03-nlp-core.md
    - "04 · RAG & Knowledge-Driven NLP": modules/04-rag-kg.md
    - "05 · Semantic Web in Practice": modules/05-semweb.md
    - "06 · Deployment & Scaling": modules/06-deploy-scale.md
