site_name: "LevelUp: AI Foundations"
site_url: https://founder-fieldnotes.github.io/levelup-courses

theme:
  name: material
  palette:
    - scheme: slate
      primary: black
      accent: amber
    - scheme: default
      primary: black
      accent: amber
  features:
    - navigation.sections
    - navigation.instant
    - navigation.top
    - content.code.copy

extra_css:
  - styles/extra.css

nav:
  - Welcome: index.md
  - Module 1: module-1.md
  - Module 2: module-2.md

plugins:
  - git-revision-date-localized
