name: Build Quiz GIFT files
on:
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  build-gift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install pyyaml
      - name: Build GIFT from YAML
        run: |
          python courses/ai-foundations/scripts/build_questions.py
      - name: Commit GIFT outputs
        run: |
          if git status --porcelain | grep -q ".gift"; then \
            git config user.name "github-actions"; \
            git config user.email "actions@github.com"; \
            git add courses/ai-foundations/question-banks/*.gift; \
            git commit -m "chore(quizzes): update GIFT exports"; \
            git push; \
          else \
            echo "No changes to commit"; \
          fi